name: CI

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: |
          cd projects/ecommerce
          npm ci
      - name: Run ESLint
        run: |
          cd projects/ecommerce
          npm run lint
      - name: Run Prettier
        run: |
          cd projects/ecommerce
          npm run format:check

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          cache: "npm"
      - name: Install dependencies
        run: |
          cd projects/ecommerce
          npm ci
      - name: Run tests
        run: |
          cd projects/ecommerce
          npm test
      - name: Upload coverage
        uses: codecov/codecov-action@v3
        with:
          directory: ./projects/ecommerce/coverage

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run SAST scan
        uses: github/codeql-action/analyze@v2
        with:
          languages: javascript, typescript
      - name: Run dependency check
        uses: snyk/actions/node@master
        with:
          args: --all-projects
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
