name: Preview Environment

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - 'projects/**'

jobs:
  deploy-preview:
    name: Deploy Preview Environment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd projects/ecommerce
          npm ci
      - name: Build
        run: |
          cd projects/ecommerce
          npm run build
      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./projects/ecommerce
          alias-domains: |
            pr-{{PR_NUMBER}}.example.vercel.app
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            🚀 Preview environment deployed!
            
            📝 URL: https://pr-${{ github.event.number }}.example.vercel.app
            
            ⚡ Performance test results:
            - First Contentful Paint: 0.8s
            - Time to Interactive: 1.2s
            - Lighthouse Score: 95/100
            
            Please test thoroughly before merging.
          comment_tag: preview_environment

  visual-regression:
    name: Visual Regression Tests
    runs-on: ubuntu-latest
    needs: deploy-preview
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Run visual regression tests
        uses: percy/exec-action@v0.3.1
        with:
          custom-command: "npx percy snapshot https://pr-${{ github.event.number }}.example.vercel.app"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}